CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INTEGER AUTO_INCREMENT,
    FIRST_NAME  VARCHAR(250) NOT NULL,
    MIDDLE_NAME VARCHAR(250),
    LAST_NAME   VARCHAR(250) NOT NULL,
    SUFFIX      VARCHAR(250),
    EMAIL       VARCHAR(250),
    PHONE       VARCHAR(250),
    PRIMARY KEY (CUSTOMER_ID)
);
